### ISSUE TITLE
farmcounter is not working

### ISSUE THREAD

**Issue by lessmarble** [joeyparrish/valheim-farmcounter#1] opened 2022-12-02 08:09 UTC
are you still managing this mod?
it has not worked since October.
if you are still active, can you check it out plz?

thanks

**Comment by joeyparrish** [comment] 2022-12-02 17:00
I haven't personally played Valheim since October, so it's very possible that an update broke this mod.  Sorry for not noticing, and thank you for the report!

What behavior do you get, if any?  Does it not do anything at all?  Does it do something crazy?

I'll take a look when I get time, possibly over the weekend.

**Comment by lessmarble** [comment] 2022-12-03 05:22
thank you for your quick response.
the mod has lost its ability to display the count.
i create a sign with $tame_boar boar
the sign reads $tame_boar boar, does not replace the variable name with the
count
let me know if I can help.

thanks again
frank

**Comment by pjotrpottervogel** [comment] 2022-12-12 09:08
the log entries for farm counter:

[Info   :   BepInEx] Loading [FarmCounter 1.0.2]
[Info   :  HarmonyX] ### Harmony id=FarmCounter, version=2.9.0.0, location=S:\Games\Steam\steamapps\common\Valheim\BepInEx\core\0Harmony.dll, env/clr=4.0.30319.42000, platform=Win32NT, ptrsize:runtime/env=8/Bits64, Windows
### Started from static void FarmCounter.FarmCounterMod::.cctor(), location S:\Games\Steam\steamapps\common\Valheim\BepInEx\plugins\FarmCounter.dll
### At 2022-12-12 09.57.40
[Info   :  HarmonyX] Patching void CraftingStation::Start() with 0 prefixes, 1 postfixes, 0 transpilers, 0 finalizers
1 postfixes:
* static void FarmCounter.FarmCounterMod+FarmCounterBehaviour+Patches::SniffWorkbenchRange(CraftingStation __instance)

[Info   :  HarmonyX] Running ILHook manipulator on void CraftingStation::Start()
[Info   :  HarmonyX] Writing postfixes
[Info   :  HarmonyX] Patching void Sign::Awake() with 0 prefixes, 1 postfixes, 0 transpilers, 0 finalizers
1 postfixes:
* static void FarmCounter.FarmCounterMod+FarmCounterBehaviour+Patches::AttachNewSignBehaviour(Sign __instance)

[Info   :  HarmonyX] Running ILHook manipulator on void Sign::Awake()
[Info   :  HarmonyX] Writing postfixes
[Info   :  HarmonyX] Patching virtual void Sign::SetText(string text) with 0 prefixes, 1 postfixes, 0 transpilers, 0 finalizers
1 postfixes:
* static void FarmCounter.FarmCounterMod+FarmCounterBehaviour+Patches::ParseNewSignText(Sign __instance)

[Info   :  HarmonyX] Running ILHook manipulator on virtual void Sign::SetText(string text)
[Info   :  HarmonyX] Writing postfixes
[Info   :  HarmonyX] Patching void Sign::UpdateText() with 0 prefixes, 0 postfixes, 1 transpilers, 0 finalizers
1 transpilers:
* static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> FarmCounter.FarmCounterMod+FarmCounterBehaviour+Patches::ReplaceDisplayedText(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions, System.Reflection.Emit.ILGenerator generator)

[Info   :  HarmonyX] Running ILHook manipulator on void Sign::UpdateText()
[Info   :  HarmonyX] Transpiling void Sign::UpdateText()
[Info   :  HarmonyX] Running transpiler static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> FarmCounter.FarmCounterMod+FarmCounterBehaviour+Patches::ReplaceDisplayedText(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions, System.Reflection.Emit.ILGenerator generator)

**Comment by Hotair10** [comment] 2023-01-23 21:28
Also hoping for an update to the mod. As Marble mentioned, it just displays the text on the sign that should be replaced, rather than replacing it.
![image](https://user-images.githubusercontent.com/5515786/214153900-e9568ddc-400e-4a77-a2dd-e821c63a3356.png)
![image](https://user-images.githubusercontent.com/5515786/214153932-becf8f87-ba21-4639-86c7-57b6fa9009a6.png)

**Comment by joeyparrish** [comment] 2023-01-24 17:54
I'll have a new build out as soon as I fix my GitHub build workflow.

**Comment by joeyparrish** [comment] 2023-01-24 18:07
v1.0.3 has been uploaded to GitHub, NexusMods and Thunderstore.  Please let me know if there are any further issues.  Enjoy!

**Comment by joeyparrish** [comment] 2023-01-24 23:39
It seems that it still isn't working.  Apologies.  I thought I had this fixed, but I was mistaken.

**Comment by joeyparrish** [comment] 2023-01-25 00:03
I changed the patch in 1.0.3, and that new patch did not crash.  However:

1. It didn't actually patch anything due to a typo in the instruction signature I was looking for
2. That patch didn't work even with the typo fixed because of some changes in how `Sign` caches text

**Comment by joeyparrish** [comment] 2023-01-25 00:24
Fixed by 59a194bf4d70a6fa022390e0589026bee2eb12c7 and e804e4108956da0d21c2e0d20bf67191b9dcb95f.

Fixes confirmed (thoroughly this time), and shipped in 1.0.**4** both on Nexus and Thunderstore.  Thanks for your patience!

**Closed as completed by joeyparrish** 2023-01-25 00:24 UTC
Labels: bug
